name: Test actions
on: 
    workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: run actions
          run: ls
        - name: run actions
          uses: ./test-py/test-py.yml
