name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    #container:
    #  image: python:3.11-bullseye

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Run script bash
      run: |
        chmod +x scripts/script.sh
        scripts/script.sh

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/test-reporter.xml
        retention-days: 1

    - name: Report coverage
      run: echo "Coverage $(cat coverage/test-reporter.xml)"
